; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:core]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<core.cpp> -<.git/> -<.svn/>
lib_deps = 
	deanisme/SevSeg@^3.7.2
	arduino-libraries/LiquidCrystal@^1.0.7

[env:button_module]
platform = atmelavr
board = nanoatmega328new
framework = arduino
build_src_filter = +<modules/button.cpp> -<.git/> -<.svn/>
lib_deps = 
	deanisme/SevSeg@^3.7.2
	arduino-libraries/LiquidCrystal@^1.0.7

[env:colors_module]
platform = atmelavr
board = nanoatmega328new
framework = arduino
build_src_filter = +<modules/colors.cpp> -<.git/> -<.svn/>
lib_deps = 
	deanisme/SevSeg@^3.7.2
	arduino-libraries/LiquidCrystal@^1.0.7

[env:morse_module]
platform = atmelavr
board = nanoatmega328new
framework = arduino
build_src_filter = +<modules/morse.cpp> -<.git/> -<.svn/>
lib_deps = 
	deanisme/SevSeg@^3.7.2
	arduino-libraries/LiquidCrystal@^1.0.7
